version: "3.7"

services:
  web:
    image: ccrisan/motioneye:master-armhf
    restart: unless-stopped
        ports:
      - "8765:80"
    user: "0:0"
    volumes:
      # Stockage de la configuration de MotionEye dans le dossier de l'app Umbrel
      - ${APP_DATA_DIR}/config:/etc/motioneye
      # Stockage des vidéos sur votre chemin personnalisé
      - /home/umbrel/umbrel/home/S5Cam:/var/lib/motioneye
      # Synchronisation de l'heure avec le Pi 4
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Asia/PhnomPenh
