services:
  web:
    image: ccrisan/motioneye:master-armhf
    restart: on-failure
    user: "0:0"
    ports:
      - "8765:8765"
    volumes:
      - ${APP_DATA_DIR}/config:/etc/motioneye
      - /home/umbrel/umbrel/home/S5Cam:/var/lib/motioneye
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Asia/PhnomPenh
