services:
  app:
    image: ghcr.io/cedwatch/netwatch:latest
    restart: unless-stopped
    ports:
      - "5218:5217"
    volumes:
      - "${APP_DATA_DIR}/data:/data"
      - "${APP_DATA_DIR}/bin:/app/bin"
    environment:
      - NETWATCH_PORT=5217
      - NETWATCH_DATA=/data

