services:
  app_proxy:
    environment:
      APP_HOST: cedwatch-orb_web_1
      APP_PORT: 7443
      PROXY_AUTH_ADD: "false"

  web:
    image: orbforge/orb:1.6.4@sha256:566b7ff77a581837e4a295ec79d30be564667fa7a2580d8c7328ab794a6fe0f2
    restart: unless-stopped
    init: true
    network_mode: host
    volumes:
      - "${APP_DATA_DIR}/config:/root/.config/orb"
