services:
  app:
    image: ghcr.io/cedwatch/rclone-backup:latest
    restart: unless-stopped
    ports:
      - "4010:80"
    volumes:
      - ${APP_DATA_DIR}/config:/data/config
      - /home/umbrel/umbrel/home/SpaceshipBak:/data/backups
